name: Call Reusable Workflow

on:
  push:
    branches: [master]
  workflow_dispatch:  # Allow manual triggering
    inputs:           #user enter them in the github actions UI
      deploy_env:
        description: "Target environment"
        required: true
        type: choice #string or choice is a dropdown  
        options:
          - staging
          - production
        default: "staging"

jobs:
  call-reusable:  # This is now the reusable workflow itself
    uses: ahmedhoss22/reusable-workflow/.github/workflows/reusable-workflow.yml@master
    with:
      environment: ${{ github.event.inputs.deploy_env }}
      custom_message: "Triggered from ${{ github.repository }}"
    secrets:
      api_key: ${{ secrets.DEPLOY_API_KEY }}   # inherit
